### ISSUE TITLE
Files URL hardcoded in database interfere with ip or domain change

### ISSUE THREAD

**Issue by nico9julio** [flagrow/upload#121]
- flagrow/upload extension version: <0.5.7>
- flarum version: 0.1.0-beta.7
- Upload adapter causing issues: image url hardcoded with servername

---

Hello! Thanks for this great extension!
After changing server IP I have noted that no image was showing up.
So I looked in database table for uploaded files and saw that the complete URL is saved, for example: http://192.168.10.99/flarum/assets/files/2017-11-02/1509651602-0-rufusuefi.png

I think this could be better if only date and filename where saved. So the script assemble the complete URL with the server URL and the image directory variable, preconfigured by UI.

Thanks!

**Comment by luceos** [comment]
Sadly that is impossible because this extension allows for multiple upload adapters. In order to understand where the image has to be included from it stores the url when uploading. A good example of this is imgur, without saving the url there would be no way to know where the file was uploaded.

Instead you could easily replace all values in your database, see: https://github.com/flagrow/upload/issues/115#issuecomment-337151912
