### ISSUE TITLE
Domain-agnostic file upload

### ISSUE THREAD

**Issue by pztrn** [flagrow/upload#171]
- flagrow/upload extension version: 0.7.1
- flarum version: 0.1.0-beta.8.1
- upload adapter causing issues: local
- mimetype configurations: irrelevant

---

I'm hosting a forum in overlay networks which accessible via more than one URL. In order uploads to work we have to manually remove domain from BBCode this extension inserts into post and patch adapter to allow attachment to be downloaded.

[This is the problematic line](https://github.com/flagrow/upload/blob/4e6fb47ce01f1a6f3592dec3d5904570cdbba07b/src/Adapters/Local.php#L42) in local adapter. I've removed whole ``else`` clause and everything works.

Can you please patch this plugin for this?

Thanks!

**Comment by luceos** [comment]
Have you tried setting `cdnUrl` to `/`?

Otherwise I see no reason why this extension should drop functionality for one specific use case.

If the above suggestion doesn't work you can alternatively create a local listener to this event to update the url: https://github.com/flagrow/upload/blob/master/src/Events/File/WillBeSaved.php
