### ISSUE TITLE
2 issues : image file type change to ’.jpeg‘, and big image file upload error.

### ISSUE THREAD

**Issue by DearTanker** [flagrow/upload#62]
- flagrow/upload extension version: 0.4.8 and some previous
- flarum version: beta6
- Upload adapter causing issues:

issues 1 : when .jpg upload , it auto change to .jpeg .

issues 2 : when upload a image with more than 2mb , get error and upload fail .PHP configer is ok with 20mb max upload（post_max_size、upload_max_filesize）,and 40s max_execution_time.

**Comment by Luceos** [comment]
- What is the exact problem you experience with renaming .jpg to .jpeg?
- Did you update the max file size in the extension setting page too, see image:

![image](https://cloud.githubusercontent.com/assets/504687/23937751/5fc0bd22-0959-11e7-8996-672c4cf5b9c1.png)

**Comment by DearTanker** [comment]
- auto rename is not necessary and it's just wrong
- of course, i have set to 20480

<img width="565" alt="qq20170315-154449 2x" src="https://cloud.githubusercontent.com/assets/1122669/23938232/5fd9df4a-0996-11e7-8067-9044509a540a.png">

**Comment by Luceos** [comment]
> auto rename is not necessary and it's just wrong

I disagree. But feel free to offer proper argumentation so at least I have the chance to reconsider, because "not necessary" and "just wrong" doesn't tell me a thing. The reason to do so is to force actual mime types to be used. This prevents abuse of the upload feature. Feel free to read [this article](http://guides.codepath.com/websecurity/File-Upload-Abuse) and tell me what you think afterward.

Related to the second thing, what error do you get. Uploads still have to be handled by the frontend, I haven't taken into account (nor done any tests with) long running uploads yet (eg movies of several hundreds megabytes).

**Comment by jordanjay29** [comment]
Mind you, there are 6 different accepted JPEG extensions (.jpg, .jpeg, .jpe, .jif, .jfif, .jfi) and they all should work the same. That's because the MIME type is all JPEG. So, no, it's not wrong and while it might not be necessary it provides some consistency for the extension (which now can look for just one file type instead of 6).

**Comment by DearTanker** [comment]
@jordanjay29 @Luceos so great thinking. i have no word to comment.

just 3.5mb jpg and i get error.

![image](https://cloud.githubusercontent.com/assets/1122669/23940981/f1051c5e-09a1-11e7-81d3-4b823f3d59db.png)

but when i use Image Upload 0.3.1, all fine.

**Comment by DearTanker** [comment]
by the way, jpg is more popular than jpeg, why not auto change to jpg.

**Comment by Luceos** [comment]
Do you see any errors in your webserver log or `storage/logs/flarum.log` file that might relate to the upload issue?

**Comment by webeindustry** [comment]
@DearTanker  You should check max_post_size in /etc/php.ini. It defaults to 2M.

**Comment by Luceos** [comment]
I've improved error handling of the upload methods. They now verify ini-settings and throw related exceptions. Not going to change logic for jpeg file types.
